version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: always

  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:80"
    env_file:
      - ./Frontend/.env
    restart: always
    depends_on:
      - backend
