version: "3.9"

services:
  backend:
    image: padma272/jobsphere-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: always

  frontend:
    image: padma272/jobsphere-frontend:latest
    ports:
      - "80:80"
    env_file:
      - ./Frontend/.env
    restart: always
    depends_on:
      - backend
